2025-05-28 10:40:54,395 - INFO - firebase - Starting Firebase event processor on path: 'datafeeds'
2025-05-28 10:40:54,917 - INFO - firebase - Firebase listener registered successfully.
2025-05-28 10:40:54,935 - INFO - firebase - Processed Firebase event. Symbols updated: ['AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDSGD', 'AUDUSD', 'BTCUSD', 'CADCHF', 'CADJPY', 'CHFJPY', 'CHFSGD', 'D30', 'EURAUD', 'EURCAD', 'EURCHF', 'EURCZK', 'EURGBP', 'EURJPY', 'EURNOK', 'EURNZD', 'EURPLN', 'EURSEK', 'EURSGD', 'EURUSD', 'EURZAR', 'GBPAUD', 'GBPNOK', 'GBPNZD', 'GBPSEK', 'GBPUSD', 'JP225', 'NOKSEK', 'NZDCAD', 'NZDJPY', 'NZDUSD', 'SGDJPY', 'US30', 'USDCAD', 'USDCHF', 'USDCNH', 'USDCZK', 'USDJPY', 'USDNOK', 'USDSEK', 'USDSGD', 'USDTRY', 'USDZAR', 'XAGUSD', 'XAUUSD']
2025-05-28 10:40:56,406 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCZK', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'GBPNOK', 'CHFJPY', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:40:58,683 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:41:00,952 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'USDJPY', 'CADCHF', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'CHFSGD', 'USDTRY', 'EURNOK', 'GBPNZD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURJPY']
2025-05-28 10:41:03,233 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'JP225', 'EURCAD', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'NOKSEK', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:05,518 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'USDSGD', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:07,780 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'USDTRY', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'NOKSEK', 'EURGBP', 'EURJPY']
2025-05-28 10:41:10,068 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'GBPAUD', 'XAUUSD', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'EURNOK', 'D30', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURGBP']
2025-05-28 10:41:12,340 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'EURPLN', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:41:14,632 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:41:16,906 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPAUD', 'XAUUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:19,195 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURGBP']
2025-05-28 10:41:21,458 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'JP225', 'USDNOK', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'AUDCHF', 'NOKSEK', 'EURGBP']
2025-05-28 10:41:23,721 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPAUD', 'XAUUSD', 'BTCUSD', 'EURNZD', 'EURZAR', 'USDZAR', 'SGDJPY', 'JP225', 'USDNOK', 'US30', 'GBPUSD', 'NZDUSD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'EURSGD', 'EURGBP']
2025-05-28 10:41:26,019 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'USDCAD']
2025-05-28 10:41:28,278 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:41:30,540 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD']
2025-05-28 10:41:32,817 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'USDCHF', 'USDNOK', 'USDSEK', 'US30', 'GBPUSD', 'AUDUSD', 'USDTRY', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:35,087 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'JP225', 'EURCAD', 'USDNOK', 'USDSEK', 'EURAUD', 'USDTRY', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:37,373 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'USDSEK', 'US30', 'GBPUSD', 'CHFSGD', 'USDTRY', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD']
2025-05-28 10:41:39,674 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'CADJPY', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:41,944 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'JP225', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:44,198 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAUUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'USDTRY', 'EURNOK', 'GBPNZD', 'NZDCAD', 'CHFJPY', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:46,464 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'USDNOK', 'US30', 'GBPUSD', 'EURAUD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'EURNOK', 'EURCHF', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:41:48,754 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'USDCHF', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURGBP']
2025-05-28 10:41:51,031 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'EURSGD']
2025-05-28 10:41:53,310 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURZAR', 'EURSEK', 'USDZAR', 'SGDJPY', 'US30', 'GBPNZD', 'EURCHF', 'NZDCAD', 'EURJPY']
2025-05-28 10:41:55,581 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'EURCAD', 'GBPUSD', 'EURAUD', 'CHFSGD', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'EURSGD', 'EURJPY']
2025-05-28 10:41:57,846 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAGUSD', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'USDZAR', 'SGDJPY', 'GBPUSD', 'EURAUD', 'CHFSGD', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'EURSGD']
2025-05-28 10:42:00,132 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:02,401 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'CHFJPY', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:42:04,680 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAGUSD', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'GBPNZD', 'EURCHF', 'NZDCAD', 'AUDCHF', 'EURSGD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:06,951 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'EURAUD', 'CHFSGD', 'NZDUSD', 'USDTRY', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'NOKSEK', 'USDCAD', 'EURJPY']
2025-05-28 10:42:09,235 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:11,512 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'US30', 'EURAUD', 'CHFSGD', 'AUDUSD', 'EURNOK', 'GBPNZD', 'D30', 'GBPNOK', 'CHFJPY', 'EURUSD', 'NOKSEK', 'EURGBP']
2025-05-28 10:42:13,800 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'GBPNOK', 'CHFJPY', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:16,074 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'CHFSGD', 'NZDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'AUDCHF', 'USDCAD', 'EURJPY']
2025-05-28 10:42:18,350 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'CHFSGD', 'NZDUSD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURJPY']
2025-05-28 10:42:20,637 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'USDSEK', 'GBPUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURJPY']
2025-05-28 10:42:22,912 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:25,176 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAUUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'EURPLN', 'SGDJPY', 'USDCHF', 'EURCAD', 'CADJPY', 'US30', 'EURAUD', 'CHFSGD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'CHFJPY', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:42:27,471 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'CHFJPY', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:42:29,723 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:32,000 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:34,282 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:36,554 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'USDZAR', 'EURPLN', 'JP225', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'US30', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:38,845 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP']
2025-05-28 10:42:41,115 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:43,402 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'USDZAR', 'SGDJPY', 'JP225', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'AUDCHF', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:45,671 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'EURAUD', 'CHFSGD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:47,955 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'CHFSGD', 'NZDUSD', 'GBPNZD', 'D30', 'AUDCHF', 'NOKSEK', 'EURSGD', 'EURJPY']
2025-05-28 10:42:50,223 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'EURZAR', 'EURSEK', 'USDZAR', 'SGDJPY', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'USDTRY', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD']
2025-05-28 10:42:52,504 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:42:54,784 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDCZK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:42:57,047 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'D30', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:42:59,339 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'CADJPY', 'US30', 'EURAUD', 'CHFSGD', 'AUDCAD', 'GBPNZD', 'D30', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:43:02,163 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'EURNOK', 'D30', 'NZDCAD', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:43:04,436 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'EURZAR', 'AUDJPY', 'USDZAR', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'NZDUSD', 'AUDCAD', 'D30', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:43:06,750 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'CADCHF', 'EURNZD', 'USDSGD', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'GBPNOK', 'EURUSD', 'AUDCHF', 'EURJPY']
2025-05-28 10:43:09,026 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'USDCHF', 'EURCAD', 'USDCZK', 'USDNOK', 'CADJPY', 'USDSEK', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'EURNOK', 'GBPNZD', 'EURCHF', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:11,286 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'SGDJPY', 'JP225', 'USDCHF', 'EURCAD', 'CADJPY', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'GBPNZD', 'D30', 'NZDCAD', 'CHFJPY', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD']
2025-05-28 10:43:13,574 - INFO - firebase - Processed Firebase event. Symbols updated: ['XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'EURAUD', 'NZDUSD', 'USDTRY', 'EURNOK', 'GBPNZD', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURJPY']
2025-05-28 10:43:15,861 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'AUDJPY', 'USDZAR', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'US30', 'GBPUSD', 'CHFSGD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'GBPNZD', 'D30', 'NZDCAD', 'CHFJPY', 'EURUSD', 'AUDCHF', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:18,155 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'USDSGD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'JP225', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'AUDCAD', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:20,445 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'USDCNH', 'EURNZD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'EURCAD', 'USDCZK', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'EURNOK', 'GBPNZD', 'NZDCAD', 'GBPNOK', 'AUDCHF', 'NOKSEK', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:22,729 - INFO - firebase - Processed Firebase event. Symbols updated: ['GBPSEK', 'XAGUSD', 'NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'CADCHF', 'EURNZD', 'EURZAR', 'EURSEK', 'USDZAR', 'EURPLN', 'USDCHF', 'EURCAD', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'NZDUSD', 'AUDUSD', 'USDTRY', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'D30', 'NZDCAD', 'GBPNOK', 'EURUSD', 'AUDCHF', 'EURSGD', 'USDCAD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:25,022 - INFO - firebase - Processed Firebase event. Symbols updated: ['NZDJPY', 'GBPAUD', 'XAUUSD', 'BTCUSD', 'USDJPY', 'USDCNH', 'EURNZD', 'EURZAR', 'AUDJPY', 'EURSEK', 'USDZAR', 'EURPLN', 'SGDJPY', 'JP225', 'USDCHF', 'USDNOK', 'CADJPY', 'USDSEK', 'US30', 'GBPUSD', 'EURAUD', 'CHFSGD', 'AUDUSD', 'AUDCAD', 'EURNOK', 'GBPNZD', 'EURCHF', 'NZDCAD', 'GBPNOK', 'CHFJPY', 'EURUSD', 'EURGBP', 'EURJPY']
2025-05-28 10:43:27,304 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:29,575 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:31,878 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:34,178 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:36,462 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:38,730 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:41,021 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:43,305 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:45,599 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:47,867 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:50,160 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:52,457 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:54,755 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:57,036 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:43:59,309 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:01,600 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:03,893 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:06,202 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:08,497 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:10,793 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:13,090 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:15,374 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:17,666 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:19,926 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:22,235 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:24,491 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:26,783 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:29,099 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:31,382 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:33,696 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:35,974 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:38,271 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:40,553 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:42,865 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:45,137 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:47,439 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:49,726 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:52,007 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:54,294 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:56,572 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:44:58,867 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:01,172 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:03,454 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:05,753 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:08,050 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:10,348 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:12,641 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:14,927 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:17,219 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:19,506 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:21,804 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:24,077 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:26,353 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:28,635 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:30,912 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:33,204 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:35,485 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:37,776 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:40,062 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:42,357 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:44,644 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:46,943 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:49,215 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:51,514 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:53,786 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:56,069 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:45:58,353 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:00,632 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:02,921 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:05,218 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:07,500 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:09,806 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:12,119 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:14,390 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:16,675 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:18,966 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:21,250 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:23,538 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:25,823 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:28,109 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:30,396 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:32,684 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:34,978 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:37,268 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:39,548 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:41,821 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:44,119 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:46,494 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:48,803 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:51,066 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:53,365 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:55,619 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:46:57,919 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:00,186 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:02,466 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:04,759 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:07,038 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:09,326 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:11,615 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:13,913 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:16,185 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:18,474 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:20,781 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:23,060 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:25,356 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:27,669 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:29,939 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:32,235 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:34,508 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:36,800 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:39,099 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:41,383 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:43,670 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:45,943 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:48,219 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:50,549 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:52,817 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:55,104 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:57,424 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
    loop.call_soon_threadsafe(asyncio.create_task, redis_publish_queue.put(data_for_queue))
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:47:59,654 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-05-28 10:48:01,948 - ERROR - firebase - Error processing Firebase event:
Traceback (most recent call last):
  File "C:\Users\Dhanush\FASTAPI\app\firebase_stream.py", line 368, in listener
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 878, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Dhanush\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
